<?php

return [
    0 => [
        'id' => 0,
        'method' => 'string',
        'message' => [
            'id' => 0,
            'entityId' => 0,
            'entityTypeId' => 'string',
            'fields' => [
                0 => [
                    'entityId' => 0,
                    'fieldType' => [
                        'id' => 'string',
                        'name' => [
                            'languages' => [
                                0 => [
                                    'parent' => 'string',
                                    'lcid' => 0,
                                    'keyboardLayoutId' => 0,
                                    'name' => 'string',
                                    'ietfLanguageTag' => 'string',
                                    'displayName' => 'string',
                                    'nativeName' => 'string',
                                    'englishName' => 'string',
                                    'twoLetterISOLanguageName' => 'string',
                                    'threeLetterISOLanguageName' => 'string',
                                    'threeLetterWindowsLanguageName' => 'string',
                                    'compareInfo' => [
                                        'name' => 'string',
                                        'version' => [
                                            'fullVersion' => 0,
                                            'sortId' => '3fa85f64-5717-4562-b3fc-2c963f66afa6',
                                        ],
                                        'lcid' => 0,
                                    ],
                                    'textInfo' => [
                                        'ansiCodePage' => 0,
                                        'oemCodePage' => 0,
                                        'macCodePage' => 0,
                                        'ebcdicCodePage' => 0,
                                        'lcid' => 0,
                                        'cultureName' => 'string',
                                        'isReadOnly' => true,
                                        'listSeparator' => 'string',
                                        'isRightToLeft' => true,
                                    ],
                                    'isNeutralCulture' => true,
                                    'cultureTypes' => 1,
                                    'numberFormat' => [
                                        'currencyDecimalDigits' => 0,
                                        'currencyDecimalSeparator' => 'string',
                                        'isReadOnly' => true,
                                        'currencyGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'numberGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'percentGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'currencyGroupSeparator' => 'string',
                                        'currencySymbol' => 'string',
                                        'naNSymbol' => 'string',
                                        'currencyNegativePattern' => 0,
                                        'numberNegativePattern' => 0,
                                        'percentPositivePattern' => 0,
                                        'percentNegativePattern' => 0,
                                        'negativeInfinitySymbol' => 'string',
                                        'negativeSign' => 'string',
                                        'numberDecimalDigits' => 0,
                                        'numberDecimalSeparator' => 'string',
                                        'numberGroupSeparator' => 'string',
                                        'currencyPositivePattern' => 0,
                                        'positiveInfinitySymbol' => 'string',
                                        'positiveSign' => 'string',
                                        'percentDecimalDigits' => 0,
                                        'percentDecimalSeparator' => 'string',
                                        'percentGroupSeparator' => 'string',
                                        'percentSymbol' => 'string',
                                        'perMilleSymbol' => 'string',
                                        'nativeDigits' => [
                                            0 => 'string',
                                        ],
                                        'digitSubstitution' => 0,
                                    ],
                                    'dateTimeFormat' => [
                                        'amDesignator' => 'string',
                                        'calendar' => [
                                            'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'algorithmType' => 0,
                                            'isReadOnly' => true,
                                            'eras' => [
                                                0 => 0,
                                            ],
                                            'twoDigitYearMax' => 0,
                                        ],
                                        'dateSeparator' => 'string',
                                        'firstDayOfWeek' => 0,
                                        'calendarWeekRule' => 0,
                                        'fullDateTimePattern' => 'string',
                                        'longDatePattern' => 'string',
                                        'longTimePattern' => 'string',
                                        'monthDayPattern' => 'string',
                                        'pmDesignator' => 'string',
                                        'rfC1123Pattern' => 'string',
                                        'shortDatePattern' => 'string',
                                        'shortTimePattern' => 'string',
                                        'sortableDateTimePattern' => 'string',
                                        'timeSeparator' => 'string',
                                        'universalSortableDateTimePattern' => 'string',
                                        'yearMonthPattern' => 'string',
                                        'abbreviatedDayNames' => [
                                            0 => 'string',
                                        ],
                                        'shortestDayNames' => [
                                            0 => 'string',
                                        ],
                                        'dayNames' => [
                                            0 => 'string',
                                        ],
                                        'abbreviatedMonthNames' => [
                                            0 => 'string',
                                        ],
                                        'monthNames' => [
                                            0 => 'string',
                                        ],
                                        'isReadOnly' => true,
                                        'nativeCalendarName' => 'string',
                                        'abbreviatedMonthGenitiveNames' => [
                                            0 => 'string',
                                        ],
                                        'monthGenitiveNames' => [
                                            0 => 'string',
                                        ],
                                    ],
                                    'calendar' => [
                                        'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                        'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                        'algorithmType' => 0,
                                        'isReadOnly' => true,
                                        'eras' => [
                                            0 => 0,
                                        ],
                                        'twoDigitYearMax' => 0,
                                    ],
                                    'optionalCalendars' => [
                                        0 => [
                                            'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'algorithmType' => 0,
                                            'isReadOnly' => true,
                                            'eras' => [
                                                0 => 0,
                                            ],
                                            'twoDigitYearMax' => 0,
                                        ],
                                    ],
                                    'useUserOverride' => true,
                                    'isReadOnly' => true,
                                ],
                            ],
                        ],
                        'description' => [
                            'languages' => [
                                0 => [
                                    'parent' => 'string',
                                    'lcid' => 0,
                                    'keyboardLayoutId' => 0,
                                    'name' => 'string',
                                    'ietfLanguageTag' => 'string',
                                    'displayName' => 'string',
                                    'nativeName' => 'string',
                                    'englishName' => 'string',
                                    'twoLetterISOLanguageName' => 'string',
                                    'threeLetterISOLanguageName' => 'string',
                                    'threeLetterWindowsLanguageName' => 'string',
                                    'compareInfo' => [
                                        'name' => 'string',
                                        'version' => [
                                            'fullVersion' => 0,
                                            'sortId' => '3fa85f64-5717-4562-b3fc-2c963f66afa6',
                                        ],
                                        'lcid' => 0,
                                    ],
                                    'textInfo' => [
                                        'ansiCodePage' => 0,
                                        'oemCodePage' => 0,
                                        'macCodePage' => 0,
                                        'ebcdicCodePage' => 0,
                                        'lcid' => 0,
                                        'cultureName' => 'string',
                                        'isReadOnly' => true,
                                        'listSeparator' => 'string',
                                        'isRightToLeft' => true,
                                    ],
                                    'isNeutralCulture' => true,
                                    'cultureTypes' => 1,
                                    'numberFormat' => [
                                        'currencyDecimalDigits' => 0,
                                        'currencyDecimalSeparator' => 'string',
                                        'isReadOnly' => true,
                                        'currencyGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'numberGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'percentGroupSizes' => [
                                            0 => 0,
                                        ],
                                        'currencyGroupSeparator' => 'string',
                                        'currencySymbol' => 'string',
                                        'naNSymbol' => 'string',
                                        'currencyNegativePattern' => 0,
                                        'numberNegativePattern' => 0,
                                        'percentPositivePattern' => 0,
                                        'percentNegativePattern' => 0,
                                        'negativeInfinitySymbol' => 'string',
                                        'negativeSign' => 'string',
                                        'numberDecimalDigits' => 0,
                                        'numberDecimalSeparator' => 'string',
                                        'numberGroupSeparator' => 'string',
                                        'currencyPositivePattern' => 0,
                                        'positiveInfinitySymbol' => 'string',
                                        'positiveSign' => 'string',
                                        'percentDecimalDigits' => 0,
                                        'percentDecimalSeparator' => 'string',
                                        'percentGroupSeparator' => 'string',
                                        'percentSymbol' => 'string',
                                        'perMilleSymbol' => 'string',
                                        'nativeDigits' => [
                                            0 => 'string',
                                        ],
                                        'digitSubstitution' => 0,
                                    ],
                                    'dateTimeFormat' => [
                                        'amDesignator' => 'string',
                                        'calendar' => [
                                            'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'algorithmType' => 0,
                                            'isReadOnly' => true,
                                            'eras' => [
                                                0 => 0,
                                            ],
                                            'twoDigitYearMax' => 0,
                                        ],
                                        'dateSeparator' => 'string',
                                        'firstDayOfWeek' => 0,
                                        'calendarWeekRule' => 0,
                                        'fullDateTimePattern' => 'string',
                                        'longDatePattern' => 'string',
                                        'longTimePattern' => 'string',
                                        'monthDayPattern' => 'string',
                                        'pmDesignator' => 'string',
                                        'rfC1123Pattern' => 'string',
                                        'shortDatePattern' => 'string',
                                        'shortTimePattern' => 'string',
                                        'sortableDateTimePattern' => 'string',
                                        'timeSeparator' => 'string',
                                        'universalSortableDateTimePattern' => 'string',
                                        'yearMonthPattern' => 'string',
                                        'abbreviatedDayNames' => [
                                            0 => 'string',
                                        ],
                                        'shortestDayNames' => [
                                            0 => 'string',
                                        ],
                                        'dayNames' => [
                                            0 => 'string',
                                        ],
                                        'abbreviatedMonthNames' => [
                                            0 => 'string',
                                        ],
                                        'monthNames' => [
                                            0 => 'string',
                                        ],
                                        'isReadOnly' => true,
                                        'nativeCalendarName' => 'string',
                                        'abbreviatedMonthGenitiveNames' => [
                                            0 => 'string',
                                        ],
                                        'monthGenitiveNames' => [
                                            0 => 'string',
                                        ],
                                    ],
                                    'calendar' => [
                                        'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                        'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                        'algorithmType' => 0,
                                        'isReadOnly' => true,
                                        'eras' => [
                                            0 => 0,
                                        ],
                                        'twoDigitYearMax' => 0,
                                    ],
                                    'optionalCalendars' => [
                                        0 => [
                                            'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                            'algorithmType' => 0,
                                            'isReadOnly' => true,
                                            'eras' => [
                                                0 => 0,
                                            ],
                                            'twoDigitYearMax' => 0,
                                        ],
                                    ],
                                    'useUserOverride' => true,
                                    'isReadOnly' => true,
                                ],
                            ],
                        ],
                        'entityTypeId' => 'string',
                        'dataType' => 'string',
                        'mandatory' => true,
                        'unique' => true,
                        'index' => 0,
                        'categoryId' => 'string',
                        'defaultValue' => 'string',
                        'units' => [
                            0 => [
                                'id' => 0,
                                'name' => [
                                    'languages' => [
                                        0 => [
                                            'parent' => 'string',
                                            'lcid' => 0,
                                            'keyboardLayoutId' => 0,
                                            'name' => 'string',
                                            'ietfLanguageTag' => 'string',
                                            'displayName' => 'string',
                                            'nativeName' => 'string',
                                            'englishName' => 'string',
                                            'twoLetterISOLanguageName' => 'string',
                                            'threeLetterISOLanguageName' => 'string',
                                            'threeLetterWindowsLanguageName' => 'string',
                                            'compareInfo' => [
                                                'name' => 'string',
                                                'version' => [
                                                    'fullVersion' => 0,
                                                    'sortId' => '3fa85f64-5717-4562-b3fc-2c963f66afa6',
                                                ],
                                                'lcid' => 0,
                                            ],
                                            'textInfo' => [
                                                'ansiCodePage' => 0,
                                                'oemCodePage' => 0,
                                                'macCodePage' => 0,
                                                'ebcdicCodePage' => 0,
                                                'lcid' => 0,
                                                'cultureName' => 'string',
                                                'isReadOnly' => true,
                                                'listSeparator' => 'string',
                                                'isRightToLeft' => true,
                                            ],
                                            'isNeutralCulture' => true,
                                            'cultureTypes' => 1,
                                            'numberFormat' => [
                                                'currencyDecimalDigits' => 0,
                                                'currencyDecimalSeparator' => 'string',
                                                'isReadOnly' => true,
                                                'currencyGroupSizes' => [
                                                    0 => 0,
                                                ],
                                                'numberGroupSizes' => [
                                                    0 => 0,
                                                ],
                                                'percentGroupSizes' => [
                                                    0 => 0,
                                                ],
                                                'currencyGroupSeparator' => 'string',
                                                'currencySymbol' => 'string',
                                                'naNSymbol' => 'string',
                                                'currencyNegativePattern' => 0,
                                                'numberNegativePattern' => 0,
                                                'percentPositivePattern' => 0,
                                                'percentNegativePattern' => 0,
                                                'negativeInfinitySymbol' => 'string',
                                                'negativeSign' => 'string',
                                                'numberDecimalDigits' => 0,
                                                'numberDecimalSeparator' => 'string',
                                                'numberGroupSeparator' => 'string',
                                                'currencyPositivePattern' => 0,
                                                'positiveInfinitySymbol' => 'string',
                                                'positiveSign' => 'string',
                                                'percentDecimalDigits' => 0,
                                                'percentDecimalSeparator' => 'string',
                                                'percentGroupSeparator' => 'string',
                                                'percentSymbol' => 'string',
                                                'perMilleSymbol' => 'string',
                                                'nativeDigits' => [
                                                    0 => 'string',
                                                ],
                                                'digitSubstitution' => 0,
                                            ],
                                            'dateTimeFormat' => [
                                                'amDesignator' => 'string',
                                                'calendar' => [
                                                    'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                    'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                    'algorithmType' => 0,
                                                    'isReadOnly' => true,
                                                    'eras' => [
                                                        0 => 0,
                                                    ],
                                                    'twoDigitYearMax' => 0,
                                                ],
                                                'dateSeparator' => 'string',
                                                'firstDayOfWeek' => 0,
                                                'calendarWeekRule' => 0,
                                                'fullDateTimePattern' => 'string',
                                                'longDatePattern' => 'string',
                                                'longTimePattern' => 'string',
                                                'monthDayPattern' => 'string',
                                                'pmDesignator' => 'string',
                                                'rfC1123Pattern' => 'string',
                                                'shortDatePattern' => 'string',
                                                'shortTimePattern' => 'string',
                                                'sortableDateTimePattern' => 'string',
                                                'timeSeparator' => 'string',
                                                'universalSortableDateTimePattern' => 'string',
                                                'yearMonthPattern' => 'string',
                                                'abbreviatedDayNames' => [
                                                    0 => 'string',
                                                ],
                                                'shortestDayNames' => [
                                                    0 => 'string',
                                                ],
                                                'dayNames' => [
                                                    0 => 'string',
                                                ],
                                                'abbreviatedMonthNames' => [
                                                    0 => 'string',
                                                ],
                                                'monthNames' => [
                                                    0 => 'string',
                                                ],
                                                'isReadOnly' => true,
                                                'nativeCalendarName' => 'string',
                                                'abbreviatedMonthGenitiveNames' => [
                                                    0 => 'string',
                                                ],
                                                'monthGenitiveNames' => [
                                                    0 => 'string',
                                                ],
                                            ],
                                            'calendar' => [
                                                'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                'algorithmType' => 0,
                                                'isReadOnly' => true,
                                                'eras' => [
                                                    0 => 0,
                                                ],
                                                'twoDigitYearMax' => 0,
                                            ],
                                            'optionalCalendars' => [
                                                0 => [
                                                    'minSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                    'maxSupportedDateTime' => '2024-01-22T13:57:01.347Z',
                                                    'algorithmType' => 0,
                                                    'isReadOnly' => true,
                                                    'eras' => [
                                                        0 => 0,
                                                    ],
                                                    'twoDigitYearMax' => 0,
                                                ],
                                            ],
                                            'useUserOverride' => true,
                                            'isReadOnly' => true,
                                        ],
                                    ],
                                ],
                            ],
                        ],
                        'hidden' => true,
                        'readOnly' => true,
                        'isDisplayName' => true,
                        'isDisplayDescription' => true,
                        'settings' => [
                            'additionalProp1' => 'string',
                            'additionalProp2' => 'string',
                            'additionalProp3' => 'string',
                        ],
                        'excludeFromDefaultView' => true,
                        'cvlId' => 'string',
                        'multivalue' => true,
                        'trackChanges' => true,
                    ],
                    'data' => 'string',
                    'revision' => 0,
                    'lastModified' => '2024-01-22T13:57:01.347Z',
                ],
            ],
            'link' => [
                'id' => 0,
                'linkTypeId' => 'string',
                'source' => [
                    'id' => 0,
                    'version' => 0,
                    'changeSet' => 0,
                    'entityTypeId' => 'string',
                    'locked' => 'string',
                    'dateCreated' => 'string',
                    'createdBy' => 'string',
                    'modifiedBy' => 'string',
                    'fieldSetId' => 'string',
                    'lastModified' => 'string',
                    'mainPictureId' => 0,
                    'mainPictureUrl' => 'string',
                    'completeness' => 0,
                    'loadLevel' => 1,
                    'fields' => [
                        0 => [
                            'entityId' => 0,
                            'fieldTypeId' => 'string',
                            'dataType' => 'string',
                            'revision' => 0,
                            'lastModified' => 'string',
                            'data' => 'string',
                        ],
                    ],
                    'links' => [
                        0 => 'string',
                    ],
                    'displayName' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'displayDescription' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'segment' => [
                        'id' => 0,
                        'name' => 'string',
                        'description' => 'string',
                    ],
                ],
                'target' => [
                    'id' => 0,
                    'version' => 0,
                    'changeSet' => 0,
                    'entityTypeId' => 'string',
                    'locked' => 'string',
                    'dateCreated' => 'string',
                    'createdBy' => 'string',
                    'modifiedBy' => 'string',
                    'fieldSetId' => 'string',
                    'lastModified' => 'string',
                    'mainPictureId' => 0,
                    'mainPictureUrl' => 'string',
                    'completeness' => 0,
                    'loadLevel' => 1,
                    'fields' => [
                        0 => [
                            'entityId' => 0,
                            'fieldTypeId' => 'string',
                            'dataType' => 'string',
                            'revision' => 0,
                            'lastModified' => 'string',
                            'data' => 'string',
                        ],
                    ],
                    'links' => [
                        0 => 'string',
                    ],
                    'displayName' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'displayDescription' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'segment' => [
                        'id' => 0,
                        'name' => 'string',
                        'description' => 'string',
                    ],
                ],
                'linkEntity' => [
                    'id' => 0,
                    'version' => 0,
                    'changeSet' => 0,
                    'entityTypeId' => 'string',
                    'locked' => 'string',
                    'dateCreated' => 'string',
                    'createdBy' => 'string',
                    'modifiedBy' => 'string',
                    'fieldSetId' => 'string',
                    'lastModified' => 'string',
                    'mainPictureId' => 0,
                    'mainPictureUrl' => 'string',
                    'completeness' => 0,
                    'loadLevel' => 1,
                    'fields' => [
                        0 => [
                            'entityId' => 0,
                            'fieldTypeId' => 'string',
                            'dataType' => 'string',
                            'revision' => 0,
                            'lastModified' => 'string',
                            'data' => 'string',
                        ],
                    ],
                    'links' => [
                        0 => 'string',
                    ],
                    'displayName' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'displayDescription' => [
                        'entityId' => 0,
                        'fieldTypeId' => 'string',
                        'dataType' => 'string',
                        'revision' => 0,
                        'lastModified' => 'string',
                        'data' => 'string',
                    ],
                    'segment' => [
                        'id' => 0,
                        'name' => 'string',
                        'description' => 'string',
                    ],
                ],
                'index' => 0,
                'linkTypeIndex' => 0,
                'inactive' => true,
                'lastModified' => '2024-01-22T13:57:01.347Z',
            ],
            'method' => 'string',
            'xml' => 'string',
            'data' => 'string',
        ],
        'status' => 'string',
        'modified' => '2024-01-22T13:57:01.347Z',
        'added' => '2024-01-22T13:57:01.347Z',
    ],
];
