<?php

return [
    [
        'entityId' => 0,
        'linkTypeId' => 'string',
        'linkIndex' => 0,
        'linkEntity' => 'string',
        'summary' => [
            'id' => 0,
            'displayName' => 'string',
            'displayDescription' => 'string',
            'version' => 'string',
            'lockedBy' => 'string',
            'createdBy' => 'string',
            'createdDate' => 'string',
            'formattedCreatedDate' => 'string',
            'modifiedBy' => 'string',
            'modifiedDate' => 'string',
            'formattedModifiedDate' => 'string',
            'resourceUrl' => 'string',
            'entityTypeId' => 'string',
            'entityTypeDisplayName' => 'string',
            'completeness' => 0,
            'fieldSetId' => 'string',
            'fieldSetName' => 'string',
            'segmentId' => 0,
            'segmentName' => 'string',
        ],
        'fields' => [
            [
                'fieldTypeId' => 'string',
                'entityId' => 0,
                'fieldTypeDisplayName' => 'string',
                'fieldTypeDescription' => 'string',
                'fieldDataType' => 'string',
                'value' => 'string',
                'displayValue' => 'string',
                'isMultiValue' => true,
                'isHidden' => true,
                'isReadOnly' => true,
                'isMandatory' => true,
                'isUnique' => true,
                'isExcludedFromDefaultView' => true,
                'includedInFieldSets' => [
                    'string',
                ],
                'categoryId' => 'string',
                'categoryName' => 'string',
                'index' => 0,
                'revision' => 0,
                'cvlId' => 'string',
                'parentCvlId' => 'string',
                'settings' => [
                    'additionalProp1' => 'string',
                    'additionalProp2' => 'string',
                    'additionalProp3' => 'string',
                ],
            ],
        ],
        'fieldValues' => [
            [
                'fieldTypeId' => 'string',
                'value' => 'string',
            ],
        ],
        'specification' => [
            [
                'entityId' => 0,
                'additionalData' => 'string',
                'name' => 'string',
                'categoryId' => 'string',
                'value' => 'string',
                'displayValue' => 'string',
                'parentCvlId' => 'string',
                'cvlId' => 'string',
                'isMultiValue' => true,
                'index' => 0,
                'isFormatted' => true,
                'specificationFieldTypeId' => 'string',
                'unit' => 'string',
                'specificationDataType' => 'string',
                'mandatory' => true,
                'isHidden' => true,
                'isReadOnly' => true,
            ],
        ],
        'specificationValues' => [
            [
                'specificationFieldTypeId' => 'string',
                'value' => 'string',
            ],
        ],
        'media' => [
            'string',
        ],
        'mediaDetails' => [
            [
                'fileId' => 0,
                'url' => 'string',
                'fileName' => 'string',
                'extension' => 'string',
                'fileSize' => 0,
                'dateCreated' => 'string',
                'lastModified' => 'string',
                'entityId' => 0,
            ],
        ],
        'inbound' => [
            'string',
        ],
        'outbound' => [
            'string',
        ],
    ],
];
